#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias make="make -j4"

alias off="sudo shutdown -h now"
alias restart="sudo reboot"

function e {
    nohup emacsclient -c -F "((fullscreen . maximized))" $@ &>/dev/null &
    disown
}

alias en="emacs -nw"

export EDITOR="emacs"

# alias ls="ls -h "

alias clear="clear && ls"

function chpwd() {
    emulate -L zsh
    clear
    if [ -n "$INSIDE_EMACS" ]; then
        print -P "\033AnSiTc %d"
    fi
}

if [ -n "$INSIDE_EMACS" ]; then
    print -P "\033AnSiTu %n"
    print -P "\033AnSiTc %d"
fi

function venv() {
  nix-shell --command zsh
}

function pyenv_init() {
  export PATH="$HOME/.pyenv/bin/:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
}

alias ovs="cd ~/school/softeng/Overseer && venv && sudo service mysql stop"
alias banal="cd ~/school/project && venv"

# clear
